Swagger UI merge (#1)
* Creating basic Swagger API

* Update continuous-inspection.yml

* Update continuous-inspection.yml

* Update continuous-inspection.yml

* Update continuous-inspection.yml

* Updating GitHub workflows

* Update continuous-inspection.yml

* Update continuous-inspection.yml

* Update continuous-inspection.yml

* Update continuous-inspection.yml

* Updatign gha-export-vulnerabilities

* Minor workflow update

* Removing pull request execution

diff --git a/.github/workflows/continuous-inspection.yml b/.github/workflows/continuous-inspection.yml
--- a/.github/workflows/continuous-inspection.yml
+++ b/.github/workflows/continuous-inspection.yml
@@ -16,9 +16,11 @@ on:
     - 'Jenkinsfile'
     - '.gitlab-ci.yml'
     - 'README.md'
-    branches: [ master ]
-  pull_request:
-    branches: [ master ]
+    - 'LICENSE'
+    branches:
+    - '**'        # matches every branch
+  #pull_request:
+  #  branches: [ master ]
 
   # Allows you to run this workflow manually from the Actions tab
   workflow_dispatch:
@@ -62,6 +64,38 @@ jobs:
         with:
             java-version: 1.8
 
+      # Get the branch name
+      - name: Extract branch name
+        shell: bash
+        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
+        id: extract_branch
+
+         # And run script to check if it exists in FOD
+      - name: Verify FOD Release
+        shell: pwsh
+        run: |
+          Write-Output "Installing PowerShellForFOD module ..."
+          Install-Module PowerShellForFOD -Scope CurrentUser -Force -Repository PSGallery
+          Write-Output "Configuring FOD API $Env:FOD_API_URI or $env.FOD_API_URI ..."
+          $PWord = ConvertTo-SecureString -String "$Env:FOD_PAT" -AsPlainText -Force
+          $Credential = New-Object -TypeName System.Management.Automation.PSCredential -ArgumentList "$Env:FOD_TENANT\$Env:FOD_USER", $PWord
+          Set-FODConfig -ApiUri $Env:FOD_API_URI -GrantType UsernamePassword -Scope api-tenant
+          Get-FODToken -Credential $Credential
+          Write-Output "Checking for existence of $Env:GITHUB_BRANCH_NAME release in application $Env:FOD_APPLICATION_NAME"
+          # Check if FOD release matching branch name exists and fail if not - we could also create/copy new release.
+          if (-not (Test-FODRelease -ApplicationName $Env:FOD_APPLICATION_NAME -ReleaseName $Env:GITHUB_BRANCH_NAME)) { throw "Release $Env:GITHUB_BRANCH_NAME does not exist - please create it!" }
+          $ReleaseId = Get-FODReleaseId -ApplicationName $Env:FOD_APPLICATION_NAME -ReleaseName $Env:GITHUB_BRANCH_NAME
+          Write-Output "::set-output name=FOD_RELEASE_ID::$ReleaseId"
+        id: verify_fod_release
+        env:
+          FOD_TENANT: ${{ secrets.FOD_TENANT }}
+          FOD_USER: ${{ secrets.FOD_USER }}
+          FOD_PAT: ${{ secrets.FOD_PAT }}
+          FOD_APPLICATION_NAME: "IWAExpress"
+          FOD_URL: "https://emea.fortify.com/"
+          FOD_API_URI: "https://api.emea.fortify.com/"
+          GITHUB_BRANCH_NAME: ${{ steps.extract_branch.outputs.branch }}
+
       # Prepare source+dependencies for upload. The default example is for a Maven project that uses pom.xml.
       # TODO: Update PACKAGE_OPTS based on the ScanCentral Client documentation for your project's included tech stack(s). Helpful hints:
       #   ScanCentral Client will download dependencies for maven (-bt mvn) and gradle (-bt gradle).
@@ -88,37 +122,73 @@ jobs:
             FOD_TENANT: ${{ secrets.FOD_TENANT }}
             FOD_USER: ${{ secrets.FOD_USER }}
             FOD_PAT: ${{ secrets.FOD_PAT }}
-            FOD_RELEASE_ID: ${{ secrets.FOD_RELEASE_ID }}
+            FOD_RELEASE_ID: ${{ steps.verify_fod_release.outputs.FOD_RELEASE_ID }}
             FOD_URL: "https://emea.fortify.com/"
             FOD_API_URL: "https://api.emea.fortify.com/"
             FOD_UPLOADER_OPTS: "-ep 2 -pp 0 -I 1 -apf"
             FOD_UPLOADER_NOTES: 'Triggered by GitHub Actions (${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})'
 
-      # Once scan completes, pull SAST issues from Fortify on Demand and generate SARIF output.
-      # TODO: Review Action inputs. For most users, these will be the same as used in the Perform SAST Scan step.
-      - name: Download Results
-        uses: fortify/gha-fod-generate-sarif@1.1.0
+      # Pull SAST issues from Fortify on Demand and generate GitHub-optimized SARIF output
+      - name: Export Results
+        uses: fortify/gha-export-vulnerabilities@v1
         with:
-            base-url: https://emea.fortify.com
-            tenant: ${{ secrets.FOD_TENANT }}
-            user: ${{ secrets.FOD_USER }}
-            password: ${{ secrets.FOD_PAT }}
-            release-id: ${{ secrets.FOD_RELEASE_ID }}
-            output: ./sarif/output.sarif
+          fod_base_url: https://emea.fortify.com
+          fod_tenant: ${{ secrets.FOD_TENANT }}
+          fod_user: ${{ secrets.FOD_USER }}
+          fod_password: ${{ secrets.FOD_PAT }}
+          fod_release_id: ${{ steps.verify_fod_release.outputs.FOD_RELEASE_ID }}
 
       # Check if SARIF output file has been created
       - name: Check file existence
         id: check_files
         uses: andstor/file-existence-action@v1
         with:
-          files: "./sarif/output.sarif"
+          files: "./gh-fortify-sast.sarif"
 
-      # Import Fortify on Demand results to GitHub Security Code Scanning
+      # Import Fortify SAST results to GitHub Security Code Scanning
       - name: Import Results
         if: steps.check_files.outputs.files_exists == 'true'
         uses: github/codeql-action/upload-sarif@v1
         with:
-            sarif_file: ./sarif/output.sarif
+          sarif_file: ./gh-fortify-sast.sarif
+
+      # Run script to check the results of the scan to determine success/failure
+      - name: Check FOD Scan Status
+        shell: pwsh
+        run: |
+          Write-Output "Configuring FOD API $Env:FOD_API_URI or $env.FOD_API_URI ..."
+          $PWord = ConvertTo-SecureString -String "$Env:FOD_PAT" -AsPlainText -Force
+          $Credential = New-Object -TypeName System.Management.Automation.PSCredential -ArgumentList "$Env:FOD_TENANT\$Env:FOD_USER", $PWord
+          Set-FODConfig -ApiUri $Env:FOD_API_URI -GrantType UsernamePassword -Scope api-tenant
+          Get-FODToken -Credential $Credential
+          Write-Output "Checking status of FOD Release $Env:FOD_RELEASE_ID"
+          $ScanSummary = Get-FODReleaseScans -ReleaseId $Env:FOD_RELEASE_ID -OrderBy completedDateTime -Limit 1
+          $ScanId = $ScanSummary.scanId
+          $ReleaseName = $ScanSummary.releaseName
+          $ScanStatus = $ScanSummary.analysisStatusType
+          $StarRating = $ScanSummary.starRating
+          $IssueCountCritical = $ScanSummary.issueCountCritical
+          $IssueCountHigh = $ScanSummary.issueCountHigh
+          $IssueCountMedium = $ScanSummary.issueCountMedium
+          $IssueCountLow = $ScanSummary.issueCountLow
+          $TotalIssues = $ScanSummary.issueCountTotal
+          Write-Output "Finished scan $ScanId with status '$ScanStatus'"
+          Write-Output "Release '$ReleaseName' has a $StarRating star rating"
+          Write-Output "Critical Issues:  $IssueCountCritical"
+          Write-Output "High Issues:      $IssueCountHigh"
+          Write-Output "Medium Issues:    $IssueCountMedium"
+          Write-Output "Low Issues:       $IssueCountLow"
+          Write-Output "Total Issues:     $IssueCountTotal"
+          # Example of using issue data
+          #if ($StarRating -lt 2) { exit 1 } # Fail if less than 2 star rating - set to your own criteria
+        env:
+          FOD_TENANT: ${{ secrets.FOD_TENANT }}
+          FOD_USER: ${{ secrets.FOD_USER }}
+          FOD_PAT: ${{ secrets.FOD_PAT }}
+          FOD_APPLICATION_NAME: "IWAExpress"
+          FOD_RELEASE_ID: ${{ steps.verify_fod_release.outputs.FOD_RELEASE_ID }}
+          FOD_URL: "https://emea.fortify.com/"
+          FOD_API_URI: "https://api.emea.fortify.com/"
 
   FoD-DAST-Scan:
     # The type of runner that the job will run on
